[project]
name = "work-day1"
version = "0.1.0"
description = "My solution for aoc23 day 1"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.7",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
lint = [
    "black>=24.10.0",
]
